services:
  - type: web
    name: R-FAB-X-STUDIO
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://r_fab_x_studio_1_user:9yax1JG5E2zUM98UhNo6mXaNtUe3IVdN@dpg-d6ap14rh46gs738ipjd0-a.oregon-postgres.render.com/r_fab_x_studio_1
      - key: DB_SSL
        value: true
      - key: NODE_ENV
        value: production
      - key: SMTP_EMAIL
        value: idealab2026emm@gmail.com
      - key: SMTP_PASSWORD
        value: nsncqufnpwtxmwvm
    autoDeploy: false

databases:
  - name: R-FAB X-STUDIO-1   
    plan: free
    databaseName: r_fab_x_studio-1
    user: admin 

